---
- name: Check if Docker and Docker Compose are not installed
  hosts: my_servers
  gather_facts: true

  tasks:
  - name: Check if Docker is not installed
    shell: which docker
    register: docker_check
    ignore_errors: true

  - name: Check if Docker Compose is not installed
    shell: which docker-compose
    register: docker_compose_check
    ignore_errors: true

  - name: Print message if Docker or Docker Compose are installed
    debug:
      msg: "Docker or Docker Compose are already installed on this server"
    when: docker_check.rc == 0 or docker_compose_check.rc == 0
...